[project]
name = "bluetooth-charge-tray"
version = "0.1.0"
description = "Shows bluetooth battery level in windows sys tray"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pystray>=0.19.5",
    "zon>=3.0.1",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.17.0",
]
